"""rebuild

Revision ID: ba65e62056c5
Revises: 5dd4bc0cc2c8
Create Date: 2024-07-17 20:30:03.453720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba65e62056c5'
down_revision = '5dd4bc0cc2c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body', sa.String(length=255), nullable=False))
    op.add_column('messages', sa.Column('username', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'username')
    op.drop_column('messages', 'body')
    # ### end Alembic commands ###
